title: sakethramanujam
description: >- # this means to ignore newlines until "baseurl:"
  saketh ramanujam's profile  
baseurl: "/saketh" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
