title: sakethramanujam
baseurl: "/saketh" # the subpath of your site, e.g. /blog
url: "http://nerdsof.tech" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
