title: sakethramanujam
baseurl: ""
url: "https://perceptiveproton.me" 
# Build settings

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    type: page
    permalink: /blog/:title/
    


disqus:
  shortname: protonblog

