title: sakethramanujam
baseurl: ""
url: "https://perceptiveproton.me" 
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
disqus:
  shortname: protonblog
permalink: /blog/:title/
  